version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/aaron/site:/srv
      - /var/www/html:/var/www/html
      - /home/aaron/caddy_data:/data
      - /home/aaron/caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
