version: "3.7"

networks:
    starr-net:
        external: true

services:
  readarr:
    container_name: readarr
    networks:
      - starr-net
    image: cr.hotio.dev/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/aaron/.config/readarr:/config
      - /data/media/books:/books #optional
      - /data/torrents:/downloads #optional
    restart: unless-stopped
