version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       networks:
            - starr-net
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=America/New York
       ports:
            - 5055:5055
       volumes:
            - /home/aaron/.config/jellyseer:/app/config
       restart: unless-stopped
