---
version: "3.2"
services:
  radarr:
    image: cr.hotio.dev/hotio/radarr
    network_mode: bridge
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
    volumes:
      - /home/aaron/.config/radarr:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped
