version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - AUTO_UPDATE=true #optional
    volumes:
      - /home/aaron/.config/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
