version: '3.7'
services:
  jellyfin:
    image: cr.hotio.dev/hotio/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/aaron/.config/jellyfin:/config
      - /home/aaron/.cache/jellyfin:/cache
      - /data/media:/media
      - /home/aaron/.config/jellyfin/web-config.json:/jellyfin/jellyfin-web/config.json
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
