version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/aaron/.config/jellyfin:/config
      - /home/aaron/.cache/jellyfin:/cache
      - /home/share/media:/media
      - /home/aaron/.config/jellyfin/web-config.json:/jellyfin/jellyfin-web/config.json
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
