version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ: "Etc/UCT"
    volumes:
      - /home/aaron/.config/bazarr:/config
      - /data/movies:/movies #optional
      - /data/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
