version: "3.7"

networks:
    starr-net:
        external: true

services:
  bazarr:
    image: cr.hotio.dev/hotio/bazarr
    container_name: bazarr
    networks:
      - starr-net
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/aaron/.config/bazarr:/config
      - /data:/data
    ports:
      - "6767:6767"
    restart: unless-stopped
