version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
    volumes:
      - /home/aaron/.config/bazarr:/config
      - /data/media/movies:/movies #optional
      - /data/media/movies:/tv #optional
    restart: unless-stopped
