version: "3.2"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/aaron/.config/bazarr:/config
      - /data/media/movies:/movies #optional
      - /data/media/tv:/tv #optional
    restart: unless-stopped
    
