version: "3.7"
services:
  bazarr:
    image: cr.hotio.dev/hotio/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/aaron/.config/bazarr:/config
      - /data/media/movies:/movies #optional
      - /data/media/tv:/tv #optional
    ports:
      - "6767:6767"
    restart: unless-stopped
