version: "3.7"

networks:
    starr-net:
        external: true

services:
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr
    networks:
      - starr-net
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/aaron/.config/lidarr:/config
      - /data/media/music:/music #optional
      - /data/torrents:/downloads #optional
    restart: unless-stopped
